FROM node:slim

# Archivo para ambiente de desarrollo

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
RUN yarn install
#RUN yarn install react-scripts@4.0.1 -g

# add app
COPY . ./

# start app
CMD ["yarn", "start"]
